services:
  postgres_db:
    image: postgres
    restart: always
    volumes:
      - prod_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 22223333
      POSTGRES_DB: ecommerce_dev
      POSTGRES_USER: root
    ports:
      - "5434:5432"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/vorn-hotel.jumpingcrab.com/fullchain.pem:/etc/letsencrypt/live/vorn-hotel.jumpingcrab.com/fullchain.pem:ro
      - /etc/letsencrypt/live/vorn-hotel.jumpingcrab.com/privkey.pem:/etc/letsencrypt/live/vorn-hotel.jumpingcrab.com/privkey.pem:ro

  backend_dev:
    build: .
    image: vorni/hotel-express-ec2
    ports:
      - 3002:3010
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - SERVERPORT=3010
      - NODE_ENV=development
      - SERVER=server_dev_1
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres_db
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 2
        delay: 15s
        order: stop-first
        failure_action: rollback
volumes:
  prod_dev:
