services:
  postgres_db:
    image: postgres
    restart: always
    volumes:
      - prod_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 22223333
      POSTGRES_DB: ecommerce_dev
      POSTGRES_USER: root
    ports:
      - "5434:5432"
  backend_dev:
    build: .
    image: vorni/hotel-express-ec2
    ports:
      - 3002:3010
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - SERVERPORT=3010
      - NODE_ENV=development
      - SERVER=server_dev_1
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres_db
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        failure_action: rollback
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
volumes:
  prod_dev:
